fix building with clang
fix error that is given because of macro overlapping cgit_filter member:

../filter.c:388:10: error: no member named '__fprintf_chk' in
'struct cgit_filter'
  388 |         filter->fprintf(filter, f, prefix);
      |         ~~~~~~  ^
/usr/include/bits/stdio2.h:92:3: note: expanded from macro 'fprintf'
   92 |   __fprintf_chk (stream, __USE_FORTIFY_LEVEL - 1, __VA_ARGS__)
      |   ^
1 error generated.

Signed-off-by: Denis Pronin <dannftk@yandex.ru>